Recycler View Added
njaLocer/Locer-Android-Client pull request #18
Opened 2020-10-03 07:29 UTC by raghavSharma1472

I have added a very basic code regarding recycler view. Right now Home fragment will just show a bunch of text, in further commits more meaningful containers will be added.

2020-10-03 07:34 UTC, s-ayush2903 commented
Can you please attach a screenshot here, it'll make reviewing easier(to me atleast)

2020-10-03 07:36 UTC, s-ayush2903 commented
@raghavSharma1472 Also create an issue with the title: _RecyclerView Required_ and in its description mention the why recyclerView needs to be added in the module. After that update the PR description and mention in it which issue this PR solves via: `Fixes #issue_number_here` ; add the issue number after the hashtag(#).

2020-10-03 09:30 UTC, s-ayush2903 requested changes
I think after incorporating the suggested changes, we can take this a step ahead

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/HomeFragment.kt
> +        val myDataset = Datasource().loadAffirmations()
We can get rid of this variable, no need of declaring it, use it directly unless it is being used at multiple sites

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/Affirmation.kt
> +//This class is basically a data model class. We will model our data here, for now I have just kept few strings
Move this comment above the class declaration. Also, while making multi-line comments instead of block comments(`//` one), use Javadoc Comments(`/** */`)

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/Datasource.kt
> +// join the retrofit data with the data model class namely Affirmation
Same as the previous one, also add a blank line after the import

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +//This class is the adapter i.e. brain of how recycler view will look
Same

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/HomeFragment.kt
> +        val myDataset = Datasource().loadAffirmations()
We can get rid of this variable, directly use it when needed, no need of creating a new variable unless it is being used at multiple sites

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/HomeFragment.kt
> +        homeBoundLayout.recyclerView.adapter =
`Ctrl+Shift+J` on this line

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/Affirmation.kt
> +//This class is basically a data model class. We will model our data here, for now I have just kept few strings
Move this comment before the declaration of the class as infos like this are supposed to be added right at the top of the file. Also, while making multi-line comments use 
Javadoc comments(`/** .. */`) instead of block comments(`//...`)

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/Datasource.kt
> +// This class is used to get data from the strings.xml file, in future we can use it to bend any data from the internet and this class will help us to
Same as previous one, also, add a blank line between the last import & the comment

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +//This class is the adapter i.e. brain of how recycler view will look
Same

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +    //This class is holding all the views that we want to display in a container of recycler view
Same

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +        val adapterLayout = LayoutInflater.from(parent.context)
Variable not needed here as well

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +        return ItemViewHolder(
`Ctrl+Shift+J` here x2

2020-10-03 09:30 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +        val item = dataset[position]
We can get rid of this variable

2020-10-04 06:09 UTC, raghavSharma1472 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +    //This class is holding all the views that we want to display in a container of recycler view
Here I have used nested class and over here I have commented outside the class about which the comment is

2020-10-04 06:37 UTC, s-ayush2903 commented on app/src/main/java/org/locer/in/recyclerView/itemAdapter.kt
> +    //This class is holding all the views that we want to display in a container of recycler view
See how comments are made in the other files, this is not the requested change

2020-10-04 08:38 UTC, s-ayush2903 approved these changes
Looks fine. Creating a ticket: RecyclerView overlaps with bottomNavBar

Merging :tada:

2020-10-04 08:47 UTC, merged

2020-10-04 08:47 UTC, s-ayush2903 commented
Created #21